version: 2.1

jobs:
  install:
    working_directory: ~/project
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - checkout
      - run: pwd
      - run: npm install
      - run: ls -la
      - persist_to_workspace:
          root: ~/
          paths:
            - "project"
  test:
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - attach_workspace:
          at: ~/
      - run: pwd
      - run: ls -la
      - run: npm run test

  build:
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run build

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build