version: 2.1

jobs:
  install:
    docker:
      - image: node:lts
    working_directory: /project

    steps:
      - checkout
    
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - persist_to_workspace:
          root: /
          paths:
            - "project"
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
  test:
    docker:
      - image: node:lts
    working_directory: /project

    steps:
      - attach_workspace:
          at: /project
      - run: ls -la
      - run: pwd

workflows:
  test-n-deploy:
    jobs:
      - install
      - test:
          requires:
            - install