version: 2.1

# Define the jobs we want to run for this project
jobs:
  install:
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - checkout
      - run: pwd
      - run: npm install
      - run: ls -la
  test:
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - checkout
      - run: npm run test
  build:
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - checkout
      - run: npm run build
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build