version: 2.1

# Jobs
jobs:
  build:
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - checkout
      - run: ls
      - run: npm install
      - run: npm run build
  
  test:
    machine: true
    resource_class: kireevroi/kanbango
    steps:
      - checkout
      - run: npm run test

# Orchestrate
workflows:
  build-and-deploy:
    jobs:
      - build
      - test:
        requires:
          - build