version: 2.1
orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: node:lts
    working_directory: /tmp
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

      - run: npm run build

      - store_artifacts:
          path: ./build

      - run: npm run test:coverage

      - codecov/upload:
          file: './coverage/clover.xml'

  # deploy:
  #   machine:
  #     enabled: true

  #   steps:
  #     - run:
  #       name: Deploy to server
  #       command: |
  #       ssh $SSH_USER@$SSH_HOST ""